[package]
name = "webusb"
description = "WebUSB API implementation in Rust"
version = "0.1.2"
authors = ["Divy Srivastava <dj.srivastava23@gmail.com>"]
edition = "2018"
repository = "https://github.com/littledivy/webusb"
license = "MIT"
keywords = [
    "usb",
    "webusb"
]

[dependencies]
rusb = "0.8.1"
libusb1-sys = "0.5.0"
serde = { version = "1", features = ["derive"] }
