name: testing

on:
  push:
    branches: [ main, trying, staging ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: test-bors
    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
