name: testing

on:
  push:
    branches: [ main, trying, staging ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: test-bors
    runs-on: [self-hosted, linux, x64]
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate coverage
      run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing -o ./lcov.info
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./lcov.info
